VAGRANTFILE_API_VERSION = '2'
Vagrant.configure(VAGRANTFILE_API_VERSION) do|config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do|vb|
    vb.customize ['modifyvm', :id, '--memory', '4096']
  end

  #Web Server
  config.vm.define 'minikube' do|web|
    web.vm.hostname = 'minikube'
    web.vm.box = 'bento/ubuntu-18.04'
    web.vm.network 'private_network', ip: '192.168.56.200'
  end
end
